version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlin.*"
      compose:
        patterns:
          - "org.jetbrains.compose*"
          - "androidx.compose*"
      androidx:
        patterns:
          - "androidx.*"
        exclude-patterns:
          - "androidx.compose*"
      ktor:
        patterns:
          - "io.ktor*"
